

-- Write SQL queries to perform the following tasks using the Sakila database:
USE sakila;

-- 1. List the number of films per category.
-- category, film y film category
SELECT c.name AS category, COUNT(f.film_id) AS number_of_films
FROM category AS c
JOIN film_category AS fc ON c.category_id = fc.category_id
JOIN film AS f ON fc.film_id = f.film_id
GROUP BY c.name
ORDER BY number_of_films DESC;

-- 2. Retrieve the store ID, city, and country for each store.
SELECT s.store_id,c.city,co.country 
FROM store AS s
join address as ad ON ad.address_id=s.address_id
JOIN city AS c ON ad.city_id = c.city_id
JOIN country AS co ON co.country_id = c.country_id;


-- 3.  Calculate the total revenue generated by each store in dollars.
SELECT s.store_id, sum(p.amount) as "total revenue"
FROM store AS s
join staff as st ON st.store_id = st.store_id
JOIN payment p ON st.staff_id = p.staff_id
GROUP BY 
    s.store_id;
    
-- 4.  Determine the average running time of films for each category.

SELECT c.name AS category, avg(f.length) AS number_of_films
FROM category AS c
JOIN film_category AS fc ON c.category_id = fc.category_id
JOIN film AS f ON fc.film_id = f.film_id
GROUP BY c.name
ORDER BY number_of_films DESC;